name = "pureautolike-license"
main = "src/worker.js"
compatibility_date = "2026-06-21"
workers_dev = true
preview_urls = false

[vars]
BETA_ENABLED = "true"
CHECKOUT_URL = ""
ALLOWED_EXTENSION_IDS = ""
WEBHOOK_SECRET = ""

[[d1_databases]]
binding = "DB"
database_name = "pureautolike_license"
database_id = "a08f1315-346d-4b1c-8b8f-02fdeb3a52eb"
